name: Generate Snapshot Feature
on: [push]

jobs:
  Build-Dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install JQ to parse JSON
      run: sudo apt-get install -y jq

    - name: Extract metadata (tags) for Docker
      

    - name: Building Docker Image usin Dockerfile
      run: docker build -t bootcamp:3.0.0 .
    